### ISSUE TITLE
I cant compile this :( (Reference Error/Type Name Missing)

### ISSUE THREAD

**Issue by CahoBlyablin** [lgv-0/BoCheat-Unturned#1]
![shit](https://user-images.githubusercontent.com/56999136/67561554-c277ea00-f725-11e9-8c40-0112bdf8677e.png)

**Comment by lgv-0** [comment]
Hey, these errors are simply reference problems. On 64 bit systems steam default installs the game to "Program Files (x86)\Steam\steamapps\common\Unturned" but if you've set a different path, moved the file *really* deep into your file system or you're on a lower architecture, you'll need to re-reference them yourself from the Unturned files. You can either do this from the references box on the right of VS, or by editing [the lists here](https://github.com/lgv-0/BoCheat-Unturned/blob/master/HInj/HInj/HInj.csproj#L42).

**Comment by CahoBlyablin** [comment]
Thank you, I compiled, but theres another problem when injecting HInj.dll to unturned: [https://imgur.com/a/AX8ya6A](url)

**Comment by lgv-0** [comment]
How you load the DLL is something we can't help you with, but I would recommend a different type of injector, because the game is .NET, and our DLL requires the Main.Yo function to be CALLED, which Extreme Injector is 1. Not made for, and 2. Will not do.
