### ISSUE TITLE
Main.Yo()

### ISSUE THREAD

**Issue by NFKRZZ** [lgv-0/BoCheat-Unturned#11]
I was wondering where do you call the Main.Yo() function from as i was able to compile the code into a dll but i dont really know where to call that function from

**Comment by lgv-0** [comment]
That is the entrypoint, something, somewhere, inside the application, must call that for the cheat to "load." This is a job for your injector, or injection method.

**Comment by Omega1031** [comment]
Any injector you suggest and know works?
