### ISSUE TITLE
Crash on inject

### ISSUE THREAD

**Issue by Omega172** [lgv-0/BoCheat-Unturned#21]
So after finally finding an injector the works upon injecting the dll the game crashes, there is nothing of use in the log files. Any help?

**Comment by lgv-0** [comment]
Game hasn't updated for half a month, can you provide any further information on how the injector functions? Also, can you make sure you place the harmony DLL in the Unturned folder directory, then try injecting?

**Comment by Omega172** [comment]
@lgv-0 I'm using the Guided Hacking Mono Injector I have had many people tell me it works and I have tested it on other games. I tried putting the 0Harmony.dll in the unturned directory and injecting and that did not work i also tried renaming the dll to just "Harmony.dll" which also didn't work.

**Comment by lgv-0** [comment]
The DLL should include the 0, can you also verify the "bocheat.main" file is also present in the Unturned director alongside harmony?

**Comment by Omega172** [comment]
@lgv-0 I can verify it is there and the game still crashes upon inject

**Comment by lgv-0** [comment]
I've ran some tests and the latest build doesn't directly conflict the game to a crash. Even though BE is technically "disabled" the Unturned launcher still executes a secondary program with "protected" memory - while the GH Injector might work for other games, Unturned is unique in the way that it launches and may require a more intuitive workaround, maybe by changing (something) apart of the game itself to trick it into thinking your DLL is okay.

**Comment by Omega172** [comment]
I'
m going to be 100% with you I'm too stupid to do that by myself could you help me?

**Comment by lgv-0** [comment]
I cannot help you directly do it but one old trick you can explore is with .NET Reflector and ReflexIL.
