### ISSUE TITLE
Do I need to add any junk code?

### ISSUE THREAD

**Issue by Diatro** [lgv-0/BoCheat-Unturned#24]
I'm just not sure. Do I need to add junk code to it before I compile it?

**Comment by Diatro** [comment]
Oh and, when I compile it. it gives me 193 errors and 28 warnings. That alright?

**Comment by Diatro** [comment]
When I compiled it, I got a lot of errors, 158 errors and 28 warnings, is that alright?

**Comment by lykanfox** [comment]
Are you building in Debug? Are you sure that all your references are in order? No, you don't need add junk code to compile it.

**Comment by Diatro** [comment]
No, I was building in release. I also have no idea how to make sure that all my references are in order.

**Comment by Diatro** [comment]
By the way, if you have a discord link could you share it to me? This way I can probably get help way faster.

**Comment by lgv-0** [comment]
Duplicate of Issue #1
