### ISSUE TITLE
injected and nothing happened

### ISSUE THREAD

**Issue by SurapatNJ** [lgv-0/BoCheat-Unturned#25]
is this injection fault?
![image](https://user-images.githubusercontent.com/33492586/84861454-4a3aac00-b09b-11ea-9ba7-2807048b18d0.png)

![image](https://user-images.githubusercontent.com/33492586/84861418-33945500-b09b-11ea-8f7b-a25328931407.png)

**Comment by lgv-0** [comment]
Sharp has always had problems, can't help you with it.
