### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Omega1031** [lgv-0/BoCheat-Unturned#5]
So I'm an idiot and I cant figure out how to use this cheat I have a mono injector and I think I have injected it properly but nothing shows up could you please help me.

**Comment by Coopyy** [comment]
1. cant use mono injector w/ battleye
2. esc to open menu

**Comment by lgv-0** [comment]
@Coopyy Yes, you can use a Mono-Injector with BattleEye. It will just require a more enclosed method for RPM/WPM.

**Comment by Omega1031** [comment]
I have BattlEye disabled but I still cannot figure out how to inject it properly because the menu doesn't show up and I don't think I'm missing any dependencies

**Comment by lgv-0** [comment]
Double check to make sure you're _using dependencies correctly._ When you inject HInj.dll into the Unturned.exe process, and in that respect, you're now setting your program directory to the _Unturned directory_. So you now need to account for what HInj.dll needs.

**Comment by Omega1031** [comment]
Is there a way I can debug to see what dependencies are missing and how would I fix that afterwards?

**Comment by lgv-0** [comment]
I believe C:\Program Files (x86)\Steam\steamapps\common\Unturned\Logs is the place to look for the output logs of the game.

**Comment by Omega1031** [comment]
Nothing shows up in the logs so I don't think its a dependency problem and I still cannot get the menu to show up so let me ask you what you use to inject the dll maybe that might be the issue.

**Comment by lgv-0** [comment]
So, if it successfully injected a console should pop up. If not, no console. Also, if you've injected ONCE and gotten the console, a file was generated that prevents secondary injections [here](https://github.com/lgv-0/BoCheat-Unturned/blob/master/HInj/HInj/Main.cs#L124). If you haven't even gotten a console to pop up, then it's safe to assume your injector hasn't injected the DLL properly to the standard.

**Comment by Omega1031** [comment]
I have never gotten a console to pop up.

**Comment by Omega1031** [comment]
I have tried three injection methods Manual Map, LoadLibrary, and Mono. And none of them have worked.

**Comment by lgv-0** [comment]
Well, if there's no console, and no file generated in the Unturned directory, then I'd point to the injector being the problem. You could explore other injectors or write your own based off of multiple open-source ones out there.

**Comment by Omega1031** [comment]
The injector I am using was made by me.

**Comment by lgv-0** [comment]
Well the important thing to understand is you're dealing with a totally different animal. Trying to force manual map to _write each instruction of a different type_ - or running a regular loadlibrary will work off of [DLLMain](https://github.com/stagfag/trashhack/blob/master/Pener%20SDK/main.cpp#L68-L73) callbacks from the [WinAPI](https://docs.microsoft.com/en-us/windows/win32/dlls/dllmain) as their function to call once mapped into a process.

 .NET runs off of [Managed Memory](https://www.jetbrains.com/help/dotmemory/NET_Memory_Management_Concepts.html), being created and interpreted at RunTime in a very [sporadic order in memory](https://www.c-sharpcorner.com/article/C-Sharp-heaping-vs-stacking-in-net-part-i/) by the [JIT Compiler](https://www.telerik.com/blogs/understanding-net-just-in-time-compilation). Attempting to insert your own instruction without consultation to this will just _not work._

A Mono-Based injector is definitely what you need, and it WILL need to call the [Main.Yo](https://github.com/lgv-0/BoCheat-Unturned/blob/master/HInj/HInj/Main.cs#L119-L129) function as stated in the [Readme](https://github.com/lgv-0/BoCheat-Unturned/blob/master/README.md). From here I can't help you as my exact method is currently "undetected" as one would say - but there's a _few_ of well-documented injectors out there that do work.

**Comment by Omega1031** [comment]
Okay I have one last question do you know of an injector that does work I don't care if its detected as I just play single player with anticheat disabled.

**Comment by Coopyy** [comment]
how you injecting when the process headers are removed
