### ISSUE TITLE
Adding No Spread

### ISSUE THREAD

**Issue by RyanCarlson23** [lgv-0/BoCheat-Unturned#7]
`ass.spreadAim = 0f;
 ass.spreadHip = 0f;
PlayerUI.updateCrosshair(0f);`
This is nospread from "Thanking" source code. Just add this line to UpdateFirearm() funtion.

P.S. I can send you a full thanking source code if you want. Feel free to Discord me RyanCarlson23#5705

**Comment by lgv-0** [comment]
This was what I found when I was *really* trying to get sway to stop swaying.

The UpdateAim hook, and the overly large UpdateFirearm function are completely resulted from "_so this didn't work, what else can I just set to 0_"

https://paste.ubuntu.com/p/sB7jhfCdwW/

I'll play around over the weekend, thanks

**Comment by lgv-0** [comment]
[Reposted - I basically ranted on how unnecessarily long the updatefirearm function is now]

https://paste.ubuntu.com/p/sB7jhfCdwW/

I'll play around over the weekend, thanks!

**Comment by lgv-0** [comment]
Thanks for the help! Also a great tool to get it testable faster for others would be forking and making a pull request off that fork - https://github.com/susam/gitpr - makes work-flowing a lot easier!
