### ISSUE TITLE
How to build the cheat succesfully

### ISSUE THREAD

**Issue by Rzv0000** [lgv-0/BoCheat-Unturned#8]
I have Visual Studio 2019 with all the packages needed and when I try to build the cheat it just gives me a bunch of errors and I have tried to build it in VS 2017 too:
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Could not resolve this reference. Could not locate the assembly "UnityEngine.CoreModule". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj			
Error	CS0246	The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Aimbot.cs	7	N/A
Error	CS0246	The type or namespace name 'SteamPlayer' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Aimbot.cs	8	N/A
Error	CS0246	The type or namespace name 'MonoBehaviour' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Aimbot.cs	11	N/A
Error	CS0246	The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Aimbot.cs	24	N/A
Error	CS0246	The type or namespace name 'Transform' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Aimbot.cs	24	N/A
Error	CS0246	The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Aimbot.cs	34	N/A
Error	CS0246	The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Aimbot.cs	34	N/A
Error	CS0246	The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Aimbot.cs	34	N/A
Error	CS0246	The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Aimbot.cs	42	N/A
Error	CS0246	The type or namespace name 'AssetBundle' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	8	N/A
Error	CS0246	The type or namespace name 'Shader' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	9	N/A
Error	CS0246	The type or namespace name 'Shader' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	12	N/A
Error	CS0246	The type or namespace name 'Shader' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	14	N/A
Error	CS0246	The type or namespace name 'Shader' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	17	N/A
Error	CS0246	The type or namespace name 'Shader' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	19	N/A
Error	CS0246	The type or namespace name 'MonoBehaviour' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	21	N/A
Error	CS0246	The type or namespace name 'Camera' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	23	N/A
Error	CS0246	The type or namespace name 'GameObject' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	24	N/A
Error	CS0246	The type or namespace name 'Light' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	25	N/A
Error	CS0246	The type or namespace name 'Transform' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	26	N/A
Error	CS0246	The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	29	N/A
Error	CS0246	The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	29	N/A
Error	CS0246	The type or namespace name 'Texture2D' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	37	N/A
Error	CS0246	The type or namespace name 'Color' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	38	N/A
Error	CS0246	The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	44	N/A
Error	CS0246	The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	49	N/A
Error	CS0246	The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	49	N/A
Error	CS0246	The type or namespace name 'Renderer' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	230	N/A
Error	CS0246	The type or namespace name 'Shader' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	231	N/A
Error	CS0246	The type or namespace name 'Color' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	232	N/A
Error	CS0246	The type or namespace name 'Renderer' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	233	N/A
Error	CS0246	The type or namespace name 'Shader' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	233	N/A
Error	CS0246	The type or namespace name 'Color' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Drawing.cs	233	N/A
Error	CS0246	The type or namespace name 'Steamworks' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Friend.cs	10	N/A
Error	CS0246	The type or namespace name 'Steamworks' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Friend.cs	11	N/A
Error	CS0246	The type or namespace name 'SteamPlayer' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Friend.cs	38	N/A
Error	CS0246	The type or namespace name 'Steamworks' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\AskScreenshot\Hold.cs	9	N/A
Error	CS0246	The type or namespace name 'UseableGun' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\Ballistics\Hold.cs	7	N/A
Error	CS0246	The type or namespace name 'UseableGun' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\Ballistics\Hold.cs	10	N/A
Error	CS0246	The type or namespace name 'BulletInfo' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\Ballistics\Hold.cs	10	N/A
Error	CS0246	The type or namespace name 'ParticleSystem' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\Ballistics\Hold.cs	10	N/A
Error	CS0246	The type or namespace name 'Attachments' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\Ballistics\Hold.cs	11	N/A
Error	CS0246	The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\Ballistics\Hold.cs	228	N/A
Error	CS0246	The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\Ballistics\Hold.cs	228	N/A
Error	CS0246	The type or namespace name 'ParticleSystem' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\Ballistics\Hold.cs	228	N/A
Error	CS0246	The type or namespace name 'UseableGun' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\Ballistics\Hold.cs	228	N/A
Error	CS0246	The type or namespace name 'Attachments' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\Ballistics\Hold.cs	228	N/A
Error	CS0246	The type or namespace name 'InteractableDoor' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\DoorAnimation\Hold.cs	5	N/A
Error	CS0246	The type or namespace name 'InteractableDoor' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\DoorAnimation\Hold.cs	9	N/A
Error	CS0246	The type or namespace name 'Transform' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\DoorAnimation\Hold.cs	9	N/A
Error	CS0246	The type or namespace name 'BoxCollider' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\DoorAnimation\Hold.cs	10	N/A
Error	CS0246	The type or namespace name 'LevelLighting' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\IsPositionUnderwater\Hold.cs	6	N/A
Error	CS0246	The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\IsPositionUnderwater\Hold.cs	6	N/A
Error	CS0246	The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\IsPositionUnderwater\Hold.cs	10	N/A
Error	CS0246	The type or namespace name 'Vector3' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\IsPositionUnderwater\Hold.cs	35	N/A
Error	CS0246	The type or namespace name 'Provider' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\lvlLoaded\Hold.cs	8	N/A
Error	CS0246	The type or namespace name 'SDG' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\lvlLoaded\Hold.cs	12	N/A
Error	CS0246	The type or namespace name 'PlayerDashboardInformationUI' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\refreshDynamicMap\Hold.cs	6	N/A
Error	CS0246	The type or namespace name 'Steamworks' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\refreshDynamicMap\Hold.cs	9	N/A
Error	CS0246	The type or namespace name 'SteamPlayer' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\refreshDynamicMap\Hold.cs	10	N/A
Error	CS0246	The type or namespace name 'ChatManager' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\sendChat\Hold.cs	6	N/A
Error	CS0246	The type or namespace name 'EChatMode' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\sendChat\Hold.cs	6	N/A
Error	CS0246	The type or namespace name 'EChatMode' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\sendChat\Hold.cs	27	N/A
Error	CS0246	The type or namespace name 'ChatManager' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\sendChat\Hold.cs	27	N/A
Error	CS0246	The type or namespace name 'PlayerInput' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\sendRaycast\Hold.cs	5	N/A
Error	CS0246	The type or namespace name 'RaycastInfo' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\sendRaycast\Hold.cs	5	N/A
Error	CS0246	The type or namespace name 'RaycastInfo' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\sendRaycast\Hold.cs	8	N/A
Error	CS0246	The type or namespace name 'PlayerUI' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\Stun\Hold.cs	6	N/A
Error	CS0246	The type or namespace name 'PlayerLook' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\UpdateAim\Hold.cs	5	N/A
Error	CS0246	The type or namespace name 'LevelLighting' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Hooks\updLighting\Hold.cs	5	N/A
Error	CS0246	The type or namespace name 'ConsoleInputOutput' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\IConsole.cs	28	N/A
Error	CS0246	The type or namespace name 'CommandWindow' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\IConsole.cs	29	N/A
Error	CS0246	The type or namespace name 'CommandInputHandler' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\IConsole.cs	30	N/A
Error	CS0246	The type or namespace name 'MonoBehaviour' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Items.cs	5	N/A
Error	CS0246	The type or namespace name 'InteractableItem' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Items.cs	156	N/A
Error	CS0246	The type or namespace name 'InteractableItem' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Items.cs	298	N/A
Error	CS0246	The type or namespace name 'InteractableItem' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Items.cs	332	N/A
Error	CS0246	The type or namespace name 'MonoBehaviour' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Menu.cs	7	N/A
Error	CS0246	The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Menu.cs	9	N/A
Error	CS0246	The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Menu.cs	10	N/A
Error	CS0246	The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Menu.cs	11	N/A
Error	CS0246	The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Menu.cs	12	N/A
Error	CS0246	The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Menu.cs	13	N/A
Error	CS0246	The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Menu.cs	14	N/A
Error	CS0246	The type or namespace name 'Rect' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Menu.cs	204	N/A
Error	CS0246	The type or namespace name 'Vector2' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Menu.cs	206	N/A
Error	CS0246	The type or namespace name 'MonoBehaviour' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Miscellaneous.cs	5	N/A
Error	CS0246	The type or namespace name 'ItemGunAsset' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Miscellaneous.cs	16	N/A
Error	CS0246	The type or namespace name 'MonoBehaviour' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\RageBot.cs	6	N/A
Error	CS0246	The type or namespace name 'SteamPlayer' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\RageBot.cs	8	N/A
Error	CS0246	The type or namespace name 'SteamPlayer' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\RageBot.cs	9	N/A
Error	CS0246	The type or namespace name 'TempSteamworksEconomy' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Skins.cs	102	N/A
Error	CS0246	The type or namespace name 'SteamInventoryResultReady_t' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Skins.cs	105	N/A
Error	CS0246	The type or namespace name 'SteamInventoryResult_t' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Skins.cs	106	N/A
Error	CS0246	The type or namespace name 'DynamicEconDetails' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Skins.cs	107	N/A
Error	CS0246	The type or namespace name 'TempSteamworksEconomy' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Skins.cs	108	N/A
Error	CS0246	The type or namespace name 'Color' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Toolkit.cs	70	N/A
Error	CS0246	The type or namespace name 'MonoBehaviour' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Vehicles.cs	7	N/A
Error	CS0246	The type or namespace name 'InteractableVehicle' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Vehicles.cs	22	N/A
Error	CS0246	The type or namespace name 'Collider' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Vehicles.cs	23	N/A
Error	CS0246	The type or namespace name 'EEngine' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Vehicles.cs	24	N/A
Error	CS0246	The type or namespace name 'InteractableVehicle' could not be found (are you missing a using directive or an assembly reference?)	HInj	C:\Users\User\Desktop\BoCheat-Unturned-master\HInj\HInj\Vehicles.cs	98	N/A
Warning		The referenced component 'UnityEngine' could not be found.	HInj			
Warning		Could not resolve this reference. Could not locate the assembly "UnityEngine.ImageConversionModule". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj			
Warning		The referenced component 'UnityEngine.VehiclesModule' could not be found.	HInj			
Warning		The referenced component 'UnityEngine.PhysicsModule' could not be found.	HInj			
Warning		Could not resolve this reference. Could not locate the assembly "UnityEngine.PhysicsModule". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj			
Warning		The referenced component 'UnityEngine.AnimationModule' could not be found.	HInj			
Warning		Could not resolve this reference. Could not locate the assembly "UnityEngine.AssetBundleModule". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj			
Warning		The referenced component 'Assembly-CSharp-firstpass' could not be found.	HInj			
Warning		Could not resolve this reference. Could not locate the assembly "Assembly-CSharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj			
Warning		The referenced component 'UnityEngine.ImageConversionModule' could not be found.	HInj			
Warning		The referenced component 'Assembly-CSharp' could not be found.	HInj			
Warning		Could not resolve this reference. Could not locate the assembly "UnityEngine.VehiclesModule". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj			
Warning		Could not resolve this reference. Could not locate the assembly "UnityEngine". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj			
Warning		Could not resolve this reference. Could not locate the assembly "UnityEngine.IMGUIModule". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj			
Warning		The referenced component 'UnityEngine.TextRenderingModule' could not be found.	HInj			
Warning		The referenced component 'UnityEngine.AssetBundleModule' could not be found.	HInj			
Warning		The referenced component 'UnityEngine.ParticleSystemModule' could not be found.	HInj			
Warning		The referenced component 'UnityEngine.AudioModule' could not be found.	HInj			
Warning		The referenced component 'UnityEngine.CoreModule' could not be found.	HInj			
Warning		Could not resolve this reference. Could not locate the assembly "Assembly-CSharp-firstpass". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj			
Warning		The referenced component 'UnityEngine.UI' could not be found.	HInj			
Warning		Could not resolve this reference. Could not locate the assembly "UnityEngine.ParticleSystemModule". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj			
Warning		Could not resolve this reference. Could not locate the assembly "UnityEngine.UI". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj			
Warning		Could not resolve this reference. Could not locate the assembly "UnityEngine.TextRenderingModule". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj			
Warning		The referenced component 'UnityEngine.IMGUIModule' could not be found.	HInj			
Warning		Could not resolve this reference. Could not locate the assembly "UnityEngine.AnimationModule". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj			
Warning		Could not resolve this reference. Could not locate the assembly "UnityEngine.AudioModule". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HInj

**Comment by lykanfox** [comment]
Hey, thanks for the interest. This same issue has been spotted before, check out this [link](https://github.com/lgv-0/BoCheat-Unturned/issues/1) for help!
